### PR TITLE
Added the class diagram(image) to architecture file.

### PR DESCRIPTION
**Pull request by FranciscoHeronildo**
Signed-off-by: Vitor Meireles Oliveira <vitorrr.meireles@hotmail.com>
Co-authored-by: Brian <brianlui2387@gmail.com>
Co-authored-by: Cleber <cjj.castro3@gmail.com>
Co-authored-by: Francisco <heronildo.2010@hotmail.com>
Co-authored-by: Rômulo <romulovinicius10@gmail.com>

## Description
Updating the Class Diagram in the Architecture Document

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

image

### CODE REVIEW

**Review by filipetoyoshima — APPROVED** [review]
That's ok

**Comment by cjjcastro** [comment]
@all-contributors please add @cjjcastro  for docs

**Comment by cjjcastro** [comment]
@all-contributors please add @cjjcastro for code

**Comment by cjjcastro** [comment]
@all-contributors please add @brian2397 for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @Hiroshi18 for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @Hiroshi18 for docs

**Comment by cjjcastro** [comment]
@all-contributors please add @RomuloSouza  for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @FranciscoHeronildo  for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @Brian2397  for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @VitorMeirelesOliveira  for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @VitorMeirelesOliveira  for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @VitorMeirelesOliveira  for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @filipetoyoshima  for docs

**Comment by Hiroshi18** [comment]
@all-contributors please add @vitorAlves7 for code

**Comment by Hiroshi18** [comment]
@all-contributors please add @Jacoapolinario  for docs

**Comment by Hiroshi18** [comment]
@all-contributors please add @Jacoapolinario for code

**Pull request merged**
