### PR TITLE
Documenting django training

### PR DESCRIPTION
**Pull request by RomuloSouza**
## Description

Adds the django rest training documentation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

selfie-2
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by Hiroshi18** [comment]
image

**Comment by filipetoyoshima** [comment]
I didn't understand the feeling on the @RomuloSouza's photo. It's bad or is it good?

This is inconsistent, please take another picture to make the acceptance possible.

**Comment by RomuloSouza** [comment]
Done

selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Review by filipetoyoshima — APPROVED** [review]
Now it's ok!

**Pull request merged**
