### PR TITLE
Created pull request template

### PR DESCRIPTION
**Pull request by RomuloSouza**
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Review by filipetoyoshima — COMMENTED** [review]
Why there is a "Breaking change" option. Isn't every change a break risk? And if this is a recognized risk, why it should be merged?

**Comment by cjjcastro** [comment]
> Why there is a "Breaking change" option. Isn't every change a break risk? And if this is a recognized risk, why it should be merged?

Seems to be valid in case of bugs found in other functionalities that were not part of the problem solved

**Review by cjjcastro — APPROVED** [review]

**Comment by Hiroshi18** [comment]
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by Hiroshi18** [comment]
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Pull request merged**
